# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYTU--94IFoJYiSDXEZXpnZprP6CVBl5
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([2,0,6,7,8,9,10,11])
y=np=np.array([3,5,8,0,7,8,4,7])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# X va Y qiymatlarini belgilash
x = np.array([2, 0, 6, 7, 8, 9, 10, 11])
y = np.array([3, 5, 8, 0, 7, 8, 4, 7])

# Grafikni chizish
plt.plot(x, y)

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# X va Y qiymatlarini belgilash
x = np.array([2, 0, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])  # 15 ta x qiymati
y = np.array([3, 5, 8, 0, 7, 8, 4, 7, 2, 6, 5, 9, 3, 4, 7])  # 15 ta y qiymati

# Grafikni chizish
plt.plot(x, y)

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# X va Y qiymatlarini belgilash
x = np.array([2, 0, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])  # 15 ta x qiymati
y = np.array([3, 5, 8, 0, 7, 8, 4, 7, 2, 6, 5, 9, 3, 4, 7])  # 15 ta y qiymati

# Grafikni chizish va marker qo'shish
plt.plot(x, y, marker='o', linestyle='-', color='b')  # marker='o' nuqtalar, linestyle va color belgilash

# Grafikni ko'rsatish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# X va Y qiymatlarini belgilash (15 ta qiymat)
x = np.array([2, 0, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])  # 15 ta x qiymati
y = np.array([3, 5, 8, 0, 7, 8, 4, 7, 2, 6, 5, 9, 3, 4, 7])  # 15 ta y qiymati

# Grafikni chizish, marker qo'shish va rangini qora qilish
plt.plot(x, y, marker='o', linestyle='-', color='k')  # marker='o' nuqtalar, linestyle va rang qora

# Grafikni ko'rsatish
plt.show()

import  matplotlib.pyplot as plt
import numpy as np

x = np.array([2,2,5,5])
y = np.array([2,10,10,2])
mycolor = ["red","green","blue","yellow"]

plt.scatter(x,y, color=mycolor)
plt.show()

import  matplotlib.pyplot as plt
import numpy as np

x = np.array([2,2,5,5])
y = np.array([2,10,10,2])

plt.scatter(x,y)
plt.show()